# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Tests for maldoca/astgen/cc_printer_base.py.

No dedicated C++ cc_printer_base_test.cc exists to port from -- its output
is only ever validated as a substring of the larger golden files under
maldoca/astgen/test/*. These tests pin the individual building blocks
directly, cross-checked against exact snippets from
maldoca/astgen/test/lambda/ast.generated.h.
"""

import unittest

from maldoca.astgen.cc_printer_base import CcPrinterBase


class CcPrinterBaseTest(unittest.TestCase):

  def test_print_license(self):
    p = CcPrinterBase()
    p.print_license()
    self.assertEqual(
        p.content(),
        """\
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
""",
    )

  def test_print_code_generation_warning(self):
    p = CcPrinterBase()
    p.print_code_generation_warning()
    self.assertEqual(
        p.content(),
        "// " + "=" * 77 + "\n"
        "// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.\n"
        "// " + "=" * 77 + "\n",
    )

  def test_print_enter_exit_namespace(self):
    p = CcPrinterBase()
    p.print_enter_namespace("maldoca::astgen")
    self.assertEqual(p.content(), "namespace maldoca {\nnamespace astgen {\n")

    p2 = CcPrinterBase()
    p2.print_exit_namespace("maldoca::astgen")
    self.assertEqual(
        p2.content(), "}  // namespace astgen\n}  // namespace maldoca\n"
    )

  def test_print_enter_exit_header_guard(self):
    p = CcPrinterBase()
    p.print_enter_header_guard("maldoca/astgen/test/lambda/ast.h")
    self.assertEqual(
        p.content(),
        "#ifndef MALDOCA_ASTGEN_TEST_LAMBDA_AST_H_\n"
        "#define MALDOCA_ASTGEN_TEST_LAMBDA_AST_H_\n",
    )

    p2 = CcPrinterBase()
    p2.print_exit_header_guard("maldoca/astgen/test/lambda/ast.h")
    self.assertEqual(
        p2.content(), "#endif  // MALDOCA_ASTGEN_TEST_LAMBDA_AST_H_\n"
    )

  def test_print_include_header(self):
    p = CcPrinterBase()
    p.print_include_header("maldoca/astgen/test/lambda/ast.h")
    self.assertEqual(
        p.content(), '#include "maldoca/astgen/test/lambda/ast.h"\n'
    )

  def test_print_include_headers_does_not_sort(self):
    # See the comment on print_include_headers: the C++ implementation
    # doesn't actually sort despite its doc comment, and callers rely on
    # that (they pass pre-sorted literals). Verify we preserve input order.
    p = CcPrinterBase()
    p.print_include_headers(["z.h", "a.h"])
    self.assertEqual(p.content(), '#include "z.h"\n#include "a.h"\n')

  def test_print_title(self):
    p = CcPrinterBase()
    p.print_title("BinaryExpression")
    self.assertEqual(
        p.content(),
        "// " + "=" * 77 + "\n"
        "// BinaryExpression\n"
        "// " + "=" * 77 + "\n",
    )


if __name__ == "__main__":
  unittest.main()
