// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_VARIANT_AST_VISITOR_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_VARIANT_AST_VISITOR_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <functional>
#include <utility>

#include "absl/log/log.h"
#include "maldoca/astgen/test/variant/ast.generated.h"

namespace maldoca {

template <typename R>
class VAstVisitor {
 public:
  virtual ~VAstVisitor() = default;

};

template <typename R>
class MutableVAstVisitor {
 public:
  virtual ~MutableVAstVisitor() = default;

};

class EmptyVAstVisitor : public VAstVisitor<void> {
 public:
  ~EmptyVAstVisitor() override = default;
};

class EmptyMutableVAstVisitor : public MutableVAstVisitor<void> {
 public:
  ~EmptyMutableVAstVisitor() override = default;
};

class DefaultVAstVisitor : public EmptyVAstVisitor {
 public:
  ~DefaultVAstVisitor() override = default;

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(const VNode &node) = 0;
};

class DefaultMutableVAstVisitor : public EmptyMutableVAstVisitor {
 public:
  ~DefaultMutableVAstVisitor() override = default;

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(VNode &node) = 0;
};

class DefaultVAstVisitorLambdaWrapper : public DefaultVAstVisitor {
 public:
  explicit DefaultVAstVisitorLambdaWrapper(
      std::function<void(const VNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(const VNode &node) override { func_(node); }

 private:
  std::function<void(const VNode &)> func_;
};

class DefaultMutableVAstVisitorLambdaWrapper : public DefaultMutableVAstVisitor {
 public:
  explicit DefaultMutableVAstVisitorLambdaWrapper(
      std::function<void(VNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(VNode &node) override { func_(node); }

 private:
  std::function<void(VNode &)> func_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_VARIANT_AST_VISITOR_GENERATED_H_
