// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_ENUM_AST_WALKER_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_ENUM_AST_WALKER_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <memory>
#include <optional>
#include <variant>
#include <vector>

#include "absl/log/log.h"
#include "maldoca/astgen/test/enum/ast.generated.h"
#include "maldoca/astgen/test/enum/ast_visitor.generated.h"

namespace maldoca {

class EAstWalker : public EAstVisitor<void> {
 public:
  explicit EAstWalker(EAstVisitor<void> *preorder_callback,
                       EAstVisitor<void> *postorder_callback)
      : preorder_callback_(preorder_callback),
        postorder_callback_(postorder_callback) {}

 private:
  [[maybe_unused]] EAstVisitor<void> *preorder_callback_;
  [[maybe_unused]] EAstVisitor<void> *postorder_callback_;
};

class MutableEAstWalker : public MutableEAstVisitor<void> {
 public:
  explicit MutableEAstWalker(MutableEAstVisitor<void> *preorder_callback,
                       MutableEAstVisitor<void> *postorder_callback)
      : preorder_callback_(preorder_callback),
        postorder_callback_(postorder_callback) {}

 private:
  [[maybe_unused]] MutableEAstVisitor<void> *preorder_callback_;
  [[maybe_unused]] MutableEAstVisitor<void> *postorder_callback_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_ENUM_AST_WALKER_GENERATED_H_
