// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_ENUM_AST_VISITOR_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_ENUM_AST_VISITOR_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <functional>
#include <utility>

#include "absl/log/log.h"
#include "maldoca/astgen/test/enum/ast.generated.h"

namespace maldoca {

template <typename R>
class EAstVisitor {
 public:
  virtual ~EAstVisitor() = default;

};

template <typename R>
class MutableEAstVisitor {
 public:
  virtual ~MutableEAstVisitor() = default;

};

class EmptyEAstVisitor : public EAstVisitor<void> {
 public:
  ~EmptyEAstVisitor() override = default;
};

class EmptyMutableEAstVisitor : public MutableEAstVisitor<void> {
 public:
  ~EmptyMutableEAstVisitor() override = default;
};

class DefaultEAstVisitor : public EmptyEAstVisitor {
 public:
  ~DefaultEAstVisitor() override = default;

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(const ENode &node) = 0;
};

class DefaultMutableEAstVisitor : public EmptyMutableEAstVisitor {
 public:
  ~DefaultMutableEAstVisitor() override = default;

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(ENode &node) = 0;
};

class DefaultEAstVisitorLambdaWrapper : public DefaultEAstVisitor {
 public:
  explicit DefaultEAstVisitorLambdaWrapper(
      std::function<void(const ENode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(const ENode &node) override { func_(node); }

 private:
  std::function<void(const ENode &)> func_;
};

class DefaultMutableEAstVisitorLambdaWrapper : public DefaultMutableEAstVisitor {
 public:
  explicit DefaultMutableEAstVisitorLambdaWrapper(
      std::function<void(ENode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(ENode &node) override { func_(node); }

 private:
  std::function<void(ENode &)> func_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_ENUM_AST_VISITOR_GENERATED_H_
