// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_TYPED_LAMBDA_AST_VISITOR_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_TYPED_LAMBDA_AST_VISITOR_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <functional>
#include <utility>

#include "absl/log/log.h"
#include "maldoca/astgen/test/typed_lambda/ast.generated.h"

namespace maldoca {

template <typename R>
class TlAstVisitor {
 public:
  virtual ~TlAstVisitor() = default;

  virtual R VisitLiteral(const TlLiteral &literal) = 0;

  virtual R VisitVariable(const TlVariable &variable) = 0;

  virtual R VisitFunctionDefinition(const TlFunctionDefinition &function_definition) = 0;

  virtual R VisitFunctionCall(const TlFunctionCall &function_call) = 0;

  virtual R VisitLiteralType(const TlLiteralType &literal_type) = 0;

  virtual R VisitFunctionType(const TlFunctionType &function_type) = 0;

  R VisitType(const TlType &type) {
    const TlType *type_ptr = &type;
    if (const TlLiteralType *literal_type = dynamic_cast<const TlLiteralType *>(type_ptr)) {
      return VisitLiteralType(*literal_type);
    } else if (const TlFunctionType *function_type = dynamic_cast<const TlFunctionType *>(type_ptr)) {
      return VisitFunctionType(*function_type);
    }

    LOG(FATAL) << "Unreachable code.";
  }

  R VisitExpression(const TlExpression &expression) {
    const TlExpression *expression_ptr = &expression;
    if (const TlLiteral *literal = dynamic_cast<const TlLiteral *>(expression_ptr)) {
      return VisitLiteral(*literal);
    } else if (const TlVariable *variable = dynamic_cast<const TlVariable *>(expression_ptr)) {
      return VisitVariable(*variable);
    } else if (const TlFunctionDefinition *function_definition = dynamic_cast<const TlFunctionDefinition *>(expression_ptr)) {
      return VisitFunctionDefinition(*function_definition);
    } else if (const TlFunctionCall *function_call = dynamic_cast<const TlFunctionCall *>(expression_ptr)) {
      return VisitFunctionCall(*function_call);
    }

    LOG(FATAL) << "Unreachable code.";
  }
};

template <typename R>
class MutableTlAstVisitor {
 public:
  virtual ~MutableTlAstVisitor() = default;

  virtual R VisitLiteral(TlLiteral &literal) = 0;

  virtual R VisitVariable(TlVariable &variable) = 0;

  virtual R VisitFunctionDefinition(TlFunctionDefinition &function_definition) = 0;

  virtual R VisitFunctionCall(TlFunctionCall &function_call) = 0;

  virtual R VisitLiteralType(TlLiteralType &literal_type) = 0;

  virtual R VisitFunctionType(TlFunctionType &function_type) = 0;

  R VisitType(TlType &type) {
    TlType *type_ptr = &type;
    if (TlLiteralType *literal_type = dynamic_cast<TlLiteralType *>(type_ptr)) {
      return VisitLiteralType(*literal_type);
    } else if (TlFunctionType *function_type = dynamic_cast<TlFunctionType *>(type_ptr)) {
      return VisitFunctionType(*function_type);
    }

    LOG(FATAL) << "Unreachable code.";
  }

  R VisitExpression(TlExpression &expression) {
    TlExpression *expression_ptr = &expression;
    if (TlLiteral *literal = dynamic_cast<TlLiteral *>(expression_ptr)) {
      return VisitLiteral(*literal);
    } else if (TlVariable *variable = dynamic_cast<TlVariable *>(expression_ptr)) {
      return VisitVariable(*variable);
    } else if (TlFunctionDefinition *function_definition = dynamic_cast<TlFunctionDefinition *>(expression_ptr)) {
      return VisitFunctionDefinition(*function_definition);
    } else if (TlFunctionCall *function_call = dynamic_cast<TlFunctionCall *>(expression_ptr)) {
      return VisitFunctionCall(*function_call);
    }

    LOG(FATAL) << "Unreachable code.";
  }
};

class EmptyTlAstVisitor : public TlAstVisitor<void> {
 public:
  ~EmptyTlAstVisitor() override = default;

  void VisitLiteral(const TlLiteral &literal) override {}

  void VisitVariable(const TlVariable &variable) override {}

  void VisitFunctionDefinition(const TlFunctionDefinition &function_definition) override {}

  void VisitFunctionCall(const TlFunctionCall &function_call) override {}

  void VisitLiteralType(const TlLiteralType &literal_type) override {}

  void VisitFunctionType(const TlFunctionType &function_type) override {}
};

class EmptyMutableTlAstVisitor : public MutableTlAstVisitor<void> {
 public:
  ~EmptyMutableTlAstVisitor() override = default;

  void VisitLiteral(TlLiteral &literal) override {}

  void VisitVariable(TlVariable &variable) override {}

  void VisitFunctionDefinition(TlFunctionDefinition &function_definition) override {}

  void VisitFunctionCall(TlFunctionCall &function_call) override {}

  void VisitLiteralType(TlLiteralType &literal_type) override {}

  void VisitFunctionType(TlFunctionType &function_type) override {}
};

class DefaultTlAstVisitor : public EmptyTlAstVisitor {
 public:
  ~DefaultTlAstVisitor() override = default;

  void VisitLiteral(const TlLiteral &literal) override {
    this->VisitNodeDefault(literal);
  }

  void VisitVariable(const TlVariable &variable) override {
    this->VisitNodeDefault(variable);
  }

  void VisitFunctionDefinition(const TlFunctionDefinition &function_definition) override {
    this->VisitNodeDefault(function_definition);
  }

  void VisitFunctionCall(const TlFunctionCall &function_call) override {
    this->VisitNodeDefault(function_call);
  }

  void VisitLiteralType(const TlLiteralType &literal_type) override {
    this->VisitNodeDefault(literal_type);
  }

  void VisitFunctionType(const TlFunctionType &function_type) override {
    this->VisitNodeDefault(function_type);
  }

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(const TlNode &node) = 0;
};

class DefaultMutableTlAstVisitor : public EmptyMutableTlAstVisitor {
 public:
  ~DefaultMutableTlAstVisitor() override = default;

  void VisitLiteral(TlLiteral &literal) override {
    this->VisitNodeDefault(literal);
  }

  void VisitVariable(TlVariable &variable) override {
    this->VisitNodeDefault(variable);
  }

  void VisitFunctionDefinition(TlFunctionDefinition &function_definition) override {
    this->VisitNodeDefault(function_definition);
  }

  void VisitFunctionCall(TlFunctionCall &function_call) override {
    this->VisitNodeDefault(function_call);
  }

  void VisitLiteralType(TlLiteralType &literal_type) override {
    this->VisitNodeDefault(literal_type);
  }

  void VisitFunctionType(TlFunctionType &function_type) override {
    this->VisitNodeDefault(function_type);
  }

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(TlNode &node) = 0;
};

class DefaultTlAstVisitorLambdaWrapper : public DefaultTlAstVisitor {
 public:
  explicit DefaultTlAstVisitorLambdaWrapper(
      std::function<void(const TlNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(const TlNode &node) override { func_(node); }

 private:
  std::function<void(const TlNode &)> func_;
};

class DefaultMutableTlAstVisitorLambdaWrapper : public DefaultMutableTlAstVisitor {
 public:
  explicit DefaultMutableTlAstVisitorLambdaWrapper(
      std::function<void(TlNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(TlNode &node) override { func_(node); }

 private:
  std::function<void(TlNode &)> func_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_TYPED_LAMBDA_AST_VISITOR_GENERATED_H_
