// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_TYPED_LAMBDA_AST_WALKER_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_TYPED_LAMBDA_AST_WALKER_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <memory>
#include <optional>
#include <variant>
#include <vector>

#include "absl/log/log.h"
#include "maldoca/astgen/test/typed_lambda/ast.generated.h"
#include "maldoca/astgen/test/typed_lambda/ast_visitor.generated.h"

namespace maldoca {

class TlAstWalker : public TlAstVisitor<void> {
 public:
  explicit TlAstWalker(TlAstVisitor<void> *preorder_callback,
                       TlAstVisitor<void> *postorder_callback)
      : preorder_callback_(preorder_callback),
        postorder_callback_(postorder_callback) {}

  void VisitLiteral(const TlLiteral &literal) override {
    if (preorder_callback_) {
      preorder_callback_->VisitLiteral(literal);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitLiteral(literal);
    }
  }

  void VisitVariable(const TlVariable &variable) override {
    if (preorder_callback_) {
      preorder_callback_->VisitVariable(variable);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitVariable(variable);
    }
  }

  void VisitFunctionDefinition(const TlFunctionDefinition &function_definition) override {
    if (preorder_callback_) {
      preorder_callback_->VisitFunctionDefinition(function_definition);
    }
    VisitVariable(*function_definition.parameter());
    VisitType(*function_definition.parameter_type());
    VisitExpression(*function_definition.body());
    if (postorder_callback_) {
      postorder_callback_->VisitFunctionDefinition(function_definition);
    }
  }

  void VisitFunctionCall(const TlFunctionCall &function_call) override {
    if (preorder_callback_) {
      preorder_callback_->VisitFunctionCall(function_call);
    }
    VisitExpression(*function_call.caller());
    VisitExpression(*function_call.callee());
    if (postorder_callback_) {
      postorder_callback_->VisitFunctionCall(function_call);
    }
  }

  void VisitLiteralType(const TlLiteralType &literal_type) override {
    if (preorder_callback_) {
      preorder_callback_->VisitLiteralType(literal_type);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitLiteralType(literal_type);
    }
  }

  void VisitFunctionType(const TlFunctionType &function_type) override {
    if (preorder_callback_) {
      preorder_callback_->VisitFunctionType(function_type);
    }
    VisitType(*function_type.parameter_type());
    VisitType(*function_type.body_type());
    if (postorder_callback_) {
      postorder_callback_->VisitFunctionType(function_type);
    }
  }

 private:
  [[maybe_unused]] TlAstVisitor<void> *preorder_callback_;
  [[maybe_unused]] TlAstVisitor<void> *postorder_callback_;
};

class MutableTlAstWalker : public MutableTlAstVisitor<void> {
 public:
  explicit MutableTlAstWalker(MutableTlAstVisitor<void> *preorder_callback,
                       MutableTlAstVisitor<void> *postorder_callback)
      : preorder_callback_(preorder_callback),
        postorder_callback_(postorder_callback) {}

  void VisitLiteral(TlLiteral &literal) override {
    if (preorder_callback_) {
      preorder_callback_->VisitLiteral(literal);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitLiteral(literal);
    }
  }

  void VisitVariable(TlVariable &variable) override {
    if (preorder_callback_) {
      preorder_callback_->VisitVariable(variable);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitVariable(variable);
    }
  }

  void VisitFunctionDefinition(TlFunctionDefinition &function_definition) override {
    if (preorder_callback_) {
      preorder_callback_->VisitFunctionDefinition(function_definition);
    }
    VisitVariable(*function_definition.parameter());
    VisitType(*function_definition.parameter_type());
    VisitExpression(*function_definition.body());
    if (postorder_callback_) {
      postorder_callback_->VisitFunctionDefinition(function_definition);
    }
  }

  void VisitFunctionCall(TlFunctionCall &function_call) override {
    if (preorder_callback_) {
      preorder_callback_->VisitFunctionCall(function_call);
    }
    VisitExpression(*function_call.caller());
    VisitExpression(*function_call.callee());
    if (postorder_callback_) {
      postorder_callback_->VisitFunctionCall(function_call);
    }
  }

  void VisitLiteralType(TlLiteralType &literal_type) override {
    if (preorder_callback_) {
      preorder_callback_->VisitLiteralType(literal_type);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitLiteralType(literal_type);
    }
  }

  void VisitFunctionType(TlFunctionType &function_type) override {
    if (preorder_callback_) {
      preorder_callback_->VisitFunctionType(function_type);
    }
    VisitType(*function_type.parameter_type());
    VisitType(*function_type.body_type());
    if (postorder_callback_) {
      postorder_callback_->VisitFunctionType(function_type);
    }
  }

 private:
  [[maybe_unused]] MutableTlAstVisitor<void> *preorder_callback_;
  [[maybe_unused]] MutableTlAstVisitor<void> *postorder_callback_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_TYPED_LAMBDA_AST_WALKER_GENERATED_H_
