// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_REGION_AST_VISITOR_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_REGION_AST_VISITOR_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <functional>
#include <utility>

#include "absl/log/log.h"
#include "maldoca/astgen/test/region/ast.generated.h"

namespace maldoca {

template <typename R>
class RAstVisitor {
 public:
  virtual ~RAstVisitor() = default;

};

template <typename R>
class MutableRAstVisitor {
 public:
  virtual ~MutableRAstVisitor() = default;

};

class EmptyRAstVisitor : public RAstVisitor<void> {
 public:
  ~EmptyRAstVisitor() override = default;
};

class EmptyMutableRAstVisitor : public MutableRAstVisitor<void> {
 public:
  ~EmptyMutableRAstVisitor() override = default;
};

class DefaultRAstVisitor : public EmptyRAstVisitor {
 public:
  ~DefaultRAstVisitor() override = default;

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(const RNode &node) = 0;
};

class DefaultMutableRAstVisitor : public EmptyMutableRAstVisitor {
 public:
  ~DefaultMutableRAstVisitor() override = default;

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(RNode &node) = 0;
};

class DefaultRAstVisitorLambdaWrapper : public DefaultRAstVisitor {
 public:
  explicit DefaultRAstVisitorLambdaWrapper(
      std::function<void(const RNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(const RNode &node) override { func_(node); }

 private:
  std::function<void(const RNode &)> func_;
};

class DefaultMutableRAstVisitorLambdaWrapper : public DefaultMutableRAstVisitor {
 public:
  explicit DefaultMutableRAstVisitorLambdaWrapper(
      std::function<void(RNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(RNode &node) override { func_(node); }

 private:
  std::function<void(RNode &)> func_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_REGION_AST_VISITOR_GENERATED_H_
