// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_MULTIPLE_INHERITANCE_AST_WALKER_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_MULTIPLE_INHERITANCE_AST_WALKER_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <memory>
#include <optional>
#include <variant>
#include <vector>

#include "absl/log/log.h"
#include "maldoca/astgen/test/multiple_inheritance/ast.generated.h"
#include "maldoca/astgen/test/multiple_inheritance/ast_visitor.generated.h"

namespace maldoca {

class MAstWalker : public MAstVisitor<void> {
 public:
  explicit MAstWalker(MAstVisitor<void> *preorder_callback,
                       MAstVisitor<void> *postorder_callback)
      : preorder_callback_(preorder_callback),
        postorder_callback_(postorder_callback) {}

  void VisitObjectMethod(const MObjectMethod &object_method) override {
    if (preorder_callback_) {
      preorder_callback_->VisitObjectMethod(object_method);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitObjectMethod(object_method);
    }
  }

 private:
  [[maybe_unused]] MAstVisitor<void> *preorder_callback_;
  [[maybe_unused]] MAstVisitor<void> *postorder_callback_;
};

class MutableMAstWalker : public MutableMAstVisitor<void> {
 public:
  explicit MutableMAstWalker(MutableMAstVisitor<void> *preorder_callback,
                       MutableMAstVisitor<void> *postorder_callback)
      : preorder_callback_(preorder_callback),
        postorder_callback_(postorder_callback) {}

  void VisitObjectMethod(MObjectMethod &object_method) override {
    if (preorder_callback_) {
      preorder_callback_->VisitObjectMethod(object_method);
    }
    if (postorder_callback_) {
      postorder_callback_->VisitObjectMethod(object_method);
    }
  }

 private:
  [[maybe_unused]] MutableMAstVisitor<void> *preorder_callback_;
  [[maybe_unused]] MutableMAstVisitor<void> *postorder_callback_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_MULTIPLE_INHERITANCE_AST_WALKER_GENERATED_H_
