// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// STOP!! DO NOT MODIFY!! THIS FILE IS AUTOMATICALLY GENERATED.
// =============================================================================

#ifndef MALDOCA_ASTGEN_TEST_MULTIPLE_INHERITANCE_AST_VISITOR_GENERATED_H_
#define MALDOCA_ASTGEN_TEST_MULTIPLE_INHERITANCE_AST_VISITOR_GENERATED_H_

// IWYU pragma: begin_keep
// NOLINTBEGIN(whitespace/line_length)
// clang-format off

#include <functional>
#include <utility>

#include "absl/log/log.h"
#include "maldoca/astgen/test/multiple_inheritance/ast.generated.h"

namespace maldoca {

template <typename R>
class MAstVisitor {
 public:
  virtual ~MAstVisitor() = default;

  virtual R VisitObjectMethod(const MObjectMethod &object_method) = 0;

  R VisitObjectMember(const MObjectMember &object_member) {
    const MObjectMember *object_member_ptr = &object_member;
    if (const MObjectMethod *object_method = dynamic_cast<const MObjectMethod *>(object_member_ptr)) {
      return VisitObjectMethod(*object_method);
    }

    LOG(FATAL) << "Unreachable code.";
  }

  R VisitFunction(const MFunction &function) {
    const MFunction *function_ptr = &function;
    if (const MObjectMethod *object_method = dynamic_cast<const MObjectMethod *>(function_ptr)) {
      return VisitObjectMethod(*object_method);
    }

    LOG(FATAL) << "Unreachable code.";
  }
};

template <typename R>
class MutableMAstVisitor {
 public:
  virtual ~MutableMAstVisitor() = default;

  virtual R VisitObjectMethod(MObjectMethod &object_method) = 0;

  R VisitObjectMember(MObjectMember &object_member) {
    MObjectMember *object_member_ptr = &object_member;
    if (MObjectMethod *object_method = dynamic_cast<MObjectMethod *>(object_member_ptr)) {
      return VisitObjectMethod(*object_method);
    }

    LOG(FATAL) << "Unreachable code.";
  }

  R VisitFunction(MFunction &function) {
    MFunction *function_ptr = &function;
    if (MObjectMethod *object_method = dynamic_cast<MObjectMethod *>(function_ptr)) {
      return VisitObjectMethod(*object_method);
    }

    LOG(FATAL) << "Unreachable code.";
  }
};

class EmptyMAstVisitor : public MAstVisitor<void> {
 public:
  ~EmptyMAstVisitor() override = default;

  void VisitObjectMethod(const MObjectMethod &object_method) override {}
};

class EmptyMutableMAstVisitor : public MutableMAstVisitor<void> {
 public:
  ~EmptyMutableMAstVisitor() override = default;

  void VisitObjectMethod(MObjectMethod &object_method) override {}
};

class DefaultMAstVisitor : public EmptyMAstVisitor {
 public:
  ~DefaultMAstVisitor() override = default;

  void VisitObjectMethod(const MObjectMethod &object_method) override {
    this->VisitNodeDefault(object_method);
  }

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(const MNode &node) = 0;
};

class DefaultMutableMAstVisitor : public EmptyMutableMAstVisitor {
 public:
  ~DefaultMutableMAstVisitor() override = default;

  void VisitObjectMethod(MObjectMethod &object_method) override {
    this->VisitNodeDefault(object_method);
  }

  // Override this method to customize the default behavior on each AST node.
  virtual void VisitNodeDefault(MNode &node) = 0;
};

class DefaultMAstVisitorLambdaWrapper : public DefaultMAstVisitor {
 public:
  explicit DefaultMAstVisitorLambdaWrapper(
      std::function<void(const MNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(const MNode &node) override { func_(node); }

 private:
  std::function<void(const MNode &)> func_;
};

class DefaultMutableMAstVisitorLambdaWrapper : public DefaultMutableMAstVisitor {
 public:
  explicit DefaultMutableMAstVisitorLambdaWrapper(
      std::function<void(MNode &)> func)
      : func_(std::move(func)) {}

  void VisitNodeDefault(MNode &node) override { func_(node); }

 private:
  std::function<void(MNode &)> func_;
};

// clang-format on
// NOLINTEND(whitespace/line_length)
// IWYU pragma: end_keep

}  // namespace maldoca

#endif  // MALDOCA_ASTGEN_TEST_MULTIPLE_INHERITANCE_AST_VISITOR_GENERATED_H_
