"""Generates test files for the conversion tests.

In each directory, only `input.js` is manually written. The other files are
generated by running this tool.

Usage: python3 generate_tests.py
"""

from concurrent import futures
import os
import shutil
import subprocess
import sys
from tqdm import tqdm


def find_google3_root() -> str:
  cwd = os.getcwd()
  parts = cwd.split(os.sep)
  if "google3" in parts:
    idx = parts.index("google3")
    return os.sep.join(parts[: idx + 1])
  if os.path.exists("WORKSPACE") or os.path.exists("BUILD"):
    return cwd
  return ""


def run_command(cmd: str) -> bytes:
  """Run a shell command and return its output."""

  tqdm.write(f"Running:\n  {cmd}")

  try:
    return subprocess.check_output(cmd, shell=True, stderr=subprocess.PIPE)
  except subprocess.CalledProcessError as e:
    tqdm.write(
        "Error running command, output:"
        f" {e.output.decode('utf-8', errors='replace')}"
    )
    sys.exit(1)


def generate_test_file(
    jsir_gen_bin: str, name: str, output_name: str, passes: str, prefix: str
):
  """Generates a test file.

  Args:
    jsir_gen_bin: Path to the jsir_gen binary.
    name: Test case name.
    output_name: The output file will be <name>/<output_name>.
    passes: Comma-separated list of JSIR passes.
    prefix: FileCheck prefix.
  """
  input_abs_path = os.path.abspath(os.path.join(name, "input.js"))
  output = run_command(
      f"{jsir_gen_bin}"
      f" --input_file {input_abs_path}"
      f" --passes='{passes}'"
  )

  output = output.strip()

  # Prepend prefix
  lines = output.split(b"\n")
  out_lines = []
  for i, line in enumerate(lines):
    if not line:
      line = f"// {prefix}-EMPTY:".encode()
    elif i == 0:
      line = f"// {prefix}:      ".encode() + line
    else:
      line = f"// {prefix}-NEXT: ".encode() + line
    out_lines.append(line)

  output = b"\n".join(out_lines) + b"\n"

  with open(name + "/" + output_name, "wb") as f:
    f.write(output)


def process_entry(jsir_gen_bin: str, entry: str):
  tqdm.write(f"Generating test: {entry}")

  generate_test_file(
      jsir_gen_bin,
      entry,
      output_name="ast.json",
      passes="source2ast",
      prefix="AST",
  )

  generate_test_file(
      jsir_gen_bin,
      entry,
      output_name="jshir.mlir",
      passes="source2ast,ast2hir",
      prefix="JSIR",  # Changed from JSHIR to JSIR
  )

  generate_test_file(
      jsir_gen_bin,
      entry,
      output_name="output.js",
      passes="source2ast,ast2source",
      prefix="SOURCE",
  )

  shutil.copyfile("run.lit.template", os.path.join(entry, "run.lit"))
  shutil.copyfile("BUILD.template.bzl", os.path.join(entry, "BUILD"))


if __name__ == "__main__":
  google3_root = find_google3_root()
  if not google3_root:
    tqdm.write("Error: Could not find google3 root")
    sys.exit(1)

  tqdm.write("Building jsir_gen...")
  try:
    subprocess.check_call(
        ["blaze", "build", "//third_party/maldoca/js/ir:jsir_gen"],
        cwd=google3_root,
    )
  except subprocess.CalledProcessError as e:
    tqdm.write(f"Error building jsir_gen: {e}")
    sys.exit(1)

  jsir_gen_bin = os.path.join(
      google3_root, "blaze-bin/third_party/maldoca/js/ir/jsir_gen"
  )

  entries = []
  dir_to_list = os.path.dirname(os.path.abspath(__file__))
  for entry in os.listdir(dir_to_list):
    full_entry_path = os.path.join(dir_to_list, entry)
    if not os.path.isdir(full_entry_path):
      continue
    entries.append(entry)

  with futures.ThreadPoolExecutor() as executor:
    futures_list = [
        executor.submit(process_entry, jsir_gen_bin, entry) for entry in entries
    ]
    for future in tqdm(
        futures.as_completed(futures_list), total=len(futures_list)
    ):
      try:
        future.result()
      except Exception as e:
        tqdm.write(f"Error processing entry: {e}")
        sys.exit(1)
