name: Build and Test (Linux)
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Test LLVM build
        run: |
          cd ${{ github.workspace }}
          bazelisk build @llvm-project//llvm:Support
      - name: Build everything
        run: |
          cd ${{ github.workspace }}
          bazelisk build //...
      - name: Test everything
        run: |
          cd ${{ github.workspace }}
          bazelisk test //...
      - run: echo "🍏 This job's status is ${{ job.status }}."
